### ISSUE TITLE
Confirm `GetCustomerResponse` is exported

### ISSUE THREAD

**Issue by piyalbasu** [stellar/typescript-wallet-sdk#159]
We want to ensure that `GetCustomerResponse` can be used external to the SDK

**Comment by CassioMG** [comment]
@piyalbasu  Yes, I can confirm `GetCustomerResponse` can be used external to the SDK as long as you are on version `1.7.0` in which we've [fixed lots of exporting](https://github.com/stellar/typescript-wallet-sdk/releases/tag/v1.7.0).

Devs can import it like this:
```
import { Types } from "@stellar/typescript-wallet-sdk";

let customerResponse: Types.GetCustomerResponse;
```
